baseURL = 'http://nutrimax.com/'
languageCode = 'es-cr'
title = 'Nutrimax Total'
copyright = "Copyright {year} | Nutrimax Total S.A."

[taxonomies]
    product_ref = 'products_refs'

[permalinks]
    products_refs = '/product/:title'